CREATE INDEX idx_users_email ON users(email) WHERE is_deleted = FALSE;
CREATE INDEX idx_users_google_id ON users(google_id);
CREATE INDEX idx_users_uuid ON users(uuid);
CREATE INDEX idx_users_is_active ON users(is_active);
CREATE INDEX idx_organisations_owner_id ON organisations(owner_id);
CREATE INDEX idx_organisations_slug ON organisations(slug);
CREATE INDEX idx_organisations_uuid ON organisations(uuid);
CREATE INDEX idx_organisations_country ON organisations(country);
CREATE INDEX idx_loads_organisation_id ON loads(organisation_id);
CREATE INDEX idx_loads_status ON loads(status);
CREATE INDEX idx_loads_uuid ON loads(uuid);
CREATE INDEX idx_loads_origin_destination ON loads(origin_city, destination_city);
CREATE INDEX idx_loads_pickup_date ON loads(pickup_date);
CREATE INDEX idx_loads_delivery_date ON loads(delivery_date);
CREATE INDEX idx_loads_created_at ON loads(created_at DESC);
CREATE INDEX idx_loads_is_public ON loads(is_public) WHERE is_deleted = FALSE;
CREATE INDEX idx_loads_ai_confidence ON loads(ai_confidence_score DESC);
CREATE INDEX idx_whatsapp_messages_phone ON whatsapp_messages(phone_number);
CREATE INDEX idx_whatsapp_messages_status ON whatsapp_messages(processing_status);
CREATE INDEX idx_whatsapp_messages_load_id ON whatsapp_messages(load_id);
CREATE INDEX idx_whatsapp_messages_created_at ON whatsapp_messages(created_at DESC);
CREATE INDEX idx_ai_parsing_logs_confidence ON ai_parsing_logs(confidence_score DESC);
CREATE INDEX idx_ai_parsing_logs_created_at ON ai_parsing_logs(created_at DESC);
CREATE INDEX idx_ai_parsing_logs_source ON ai_parsing_logs(source_type, source_id);
CREATE INDEX idx_moderation_queue_status ON moderation_queue(status);
CREATE INDEX idx_moderation_queue_priority ON moderation_queue(priority);
CREATE INDEX idx_moderation_queue_assigned_to ON moderation_queue(assigned_to);
CREATE INDEX idx_moderation_queue_created_at ON moderation_queue(created_at DESC);
CREATE INDEX idx_wallets_user_id ON wallets(user_id);
CREATE INDEX idx_wallets_uuid ON wallets(uuid);
CREATE INDEX idx_payments_user_id ON payments(user_id);
CREATE INDEX idx_payments_status ON payments(status);
CREATE INDEX idx_payments_created_at ON payments(created_at DESC);
CREATE INDEX idx_payments_paynow_reference ON payments(paynow_reference);
CREATE INDEX idx_unlocks_load_id ON unlocks(load_id);
CREATE INDEX idx_unlocks_user_id ON unlocks(user_id);
CREATE INDEX idx_unlocks_payment_id ON unlocks(payment_id);
CREATE INDEX idx_unlocks_created_at ON unlocks(created_at DESC);
CREATE INDEX idx_unlocks_access_expires_at ON unlocks(access_expires_at);
CREATE INDEX idx_disputes_user_id ON disputes(user_id);
CREATE INDEX idx_disputes_status ON disputes(status);
CREATE INDEX idx_disputes_created_at ON disputes(created_at DESC);
CREATE INDEX idx_disputes_resolved_by ON disputes(resolved_by);
CREATE INDEX idx_notifications_user_id ON notifications(user_id);
CREATE INDEX idx_notifications_is_read ON notifications(is_read);
CREATE INDEX idx_notifications_created_at ON notifications(created_at DESC);
CREATE INDEX idx_audit_logs_user_id ON audit_logs(user_id);
CREATE INDEX idx_audit_logs_organisation_id ON audit_logs(organisation_id);
CREATE INDEX idx_audit_logs_entity_type_id ON audit_logs(entity_type, entity_id);
CREATE INDEX idx_audit_logs_action ON audit_logs(action);
CREATE INDEX idx_audit_logs_created_at ON audit_logs(created_at DESC);
CREATE INDEX idx_fraud_reports_load_id ON fraud_reports(load_id);
CREATE INDEX idx_fraud_reports_status ON fraud_reports(status);
CREATE INDEX idx_fraud_reports_created_at ON fraud_reports(created_at DESC);
CREATE INDEX idx_sessions_user_id ON sessions(user_id);
CREATE INDEX idx_sessions_is_active ON sessions(is_active);
CREATE INDEX idx_sessions_expires_at ON sessions(expires_at);
CREATE INDEX idx_roles_organisation_id ON roles(organisation_id);
CREATE INDEX idx_user_roles_user_id ON user_roles(user_id);
CREATE INDEX idx_user_roles_organisation_id ON user_roles(organisation_id);